### ISSUE TITLE
Basket container array of array

### ISSUE THREAD

**Issue by jabawack81** [Cherrylady/checkout-system#4]
I think would be a better solution to add first here 
https://github.com/Cherrylady/checkout-system/blob/d7d5721c0a04d5c5a7f0e83b678e399af0921094/lib/price.rb#L15

instead of flattening here
https://github.com/Cherrylady/checkout-system/blob/d7d5721c0a04d5c5a7f0e83b678e399af0921094/lib/price.rb#L21

it will make the code more readable and there is better to store the data in the proper format from the beginning.

**Comment by Cherrylady** [comment]
Done
