### ISSUE TITLE
add Gemfile

### ISSUE THREAD

**Issue by jabawack81** [Cherrylady/checkout-system#6]
it could be a good idea to add a Gemfile because I just cloned the project in a new pc to test it but I had to manually install pry so maybe could be a good idea to add it to the Gemfile and use it to set the version of ruby to something bigger to 2.4 because I just found this article: https://blog.bigbinary.com/2016/11/02/ruby-2-4-introduces-enumerable-sum.html and like I remembered last night Array.sum is a new function introduced in that version

**Comment by Cherrylady** [comment]
Gemfile is unnecessary. Pry is removed.

**Comment by jabawack81** [comment]
like in the issue #7 I think this should be interview ready and so there should be a way to force the user to select a specific version of ruby so if not a Gemfile maybe a .ruby-version file

**Comment by Cherrylady** [comment]
done
