### ISSUE TITLE
Make the code interview ready

### ISSUE THREAD

**Issue by jabawack81** [Cherrylady/checkout-system#7]
This is an exercise for the interview so I think it should implement the best practices so

this should be a map and use the shorthand version
https://github.com/Cherrylady/checkout-system/blob/d7d5721c0a04d5c5a7f0e83b678e399af0921094/lib/price.rb#L21

you forgot to delete this:
https://github.com/Cherrylady/checkout-system/blob/6657109ead5f7c0092b72bbc7ddbc367465e7c62/lib/price.rb#L23

I just found a method (https://ruby-doc.org/core-2.2.3/Enumerable.html#method-i-find) that could replace the select.first method
https://github.com/Cherrylady/checkout-system/blob/6657109ead5f7c0092b72bbc7ddbc367465e7c62/lib/price.rb#L13

**Comment by Cherrylady** [comment]
done
